#!/bin/bash

# Verifica se git è installato
if ! command -v git &> /dev/null
then
  echo "gitnon è installato"
  exit 1
fi

if ! command -v git-flow &> /dev/null
then
  echo "git-flow non è installato"
  exit 1
fi

# Ottieni l'ultimo tag
last_tag=$(git describe --tags --abbrev=0)

# Estrai il numero di patch
patch=$(echo $last_tag | awk -F. '{print $3}')

# Incrementa il numero di patch
new_patch=$((patch + 1))

# Crea il nuovo numero di versione
new_version=$(echo $last_tag | sed "s/$patch/$new_patch/")

echo git flow release start "$new_version"
read -p
git flow release start "$new_version"
echo git flow release finish "$new_version"
read -p
git flow release finish "$new_version"

