apiVersion: v1
kind: Namespace
metadata:
  name: cluster-tester
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: cluster-tester
type: Opaque
data:
  password: cm9vdA==
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: cluster-tester
type: Opaque
data:
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: cluster-tester
type: Opaque
stringData:
  redis-password: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-tester
  namespace: cluster-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-tester
  template:
    metadata:
      labels:
        app: cluster-tester
    spec:
      containers:
      - name: cluster-tester
        image: manzolo/microk8s-cluster-tester:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-password
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"