apiVersion: v1
kind: Namespace
metadata:
  name: demo-go

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-go-ingress
  namespace: demo-go
spec:
  rules:
  - host: demo-go.loc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-go
            port:
              number: 80

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-go
  namespace: demo-go
  labels:
    app: demo-go
spec:
  replicas: 10
  selector:
    matchLabels:
      app: demo-go
  template:
    metadata:
      labels:
        app: demo-go
    spec:
      containers:
      - name: demo-go
        image: manzolo/demo-go:0.1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http-web-svc

---

apiVersion: v1
kind: Service
metadata:
  name: demo-go
  namespace: demo-go
spec:
  selector:
    app: demo-go
  ports:
    - port: 80
      targetPort: http-web-svc
      protocol: TCP
      nodePort: 31001
  type: NodePort
