apiVersion: v1
kind: Namespace
metadata:
  name: demo-php

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-php-ingress
  namespace: demo-php
spec:
  rules:
  - host: demo-php.loc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-php
            port:
              number: 80

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-php
  namespace: demo-php
  labels:
    app: demo-php
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demo-php
  template:
    metadata:
      labels:
        app: demo-php
    spec:
      containers:
      - name: demo-php
        image: manzolo/demo-php:0.2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http-web-svc

---

apiVersion: v1
kind: Service
metadata:
  name: demo-php
  namespace: demo-php
spec:
  selector:
    app: demo-php
  ports:
    - port: 80
      targetPort: http-web-svc
      protocol: TCP
      nodePort: 31002
  type: NodePort
