apiVersion: v1
kind: Namespace
metadata:
  name: static-site

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: static-site-ingress
  namespace: static-site
spec:
  rules:
  - host: static.loc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: static-site
            port:
              number: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-site
  namespace: static-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-site
  template:
    metadata:
      labels:
        app: static-site
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: static-site
  namespace: static-site
spec:
  selector:
    app: static-site
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31003
  type: NodePort
